pipeline:
  publish:
    image: plugins/docker
    registry: walmartdigital.azurecr.io
    repo: walmartdigital.azurecr.io/sonar-scanner-drone-plugin
    secrets: [docker_username, docker_password]
    tags:
      - ${DRONE_BUILD_NUMBER}
      - latest
    when:
      event: [push]
      branch: [master]